FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ./ ./
RUN mkdir -p /app/publish/wwwroot/Images/Logos && \
    dotnet publish ./src/Apps/WebApp/Nutri.Veda.WebApp/Nutri.Veda.WebApp \
    -c Release \
    --os linux \
    --arch x64 \
    -p:PublishTrimmed=false \
    -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update && \
    apt-get install -y --no-install-recommends telnet iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create directory for DataProtection keys
RUN mkdir -p /tmp/keys && chmod 755 /tmp/keys

ENTRYPOINT ["dotnet", "Nutri.Veda.WebApp.dll"]

